esphome:
  name: watertankpoc
  friendly_name: WaterTankPOC

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "wW+soPYS+IgsZ7q44OQWlq28UmanaEdRp3otQ+Tcl7A="

ota:
  - platform: esphome
    password: "06dee23b62052546b00020f13715c23c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watertankpoc Fallback Hotspot"
    password: "jlr12345678"

web_server:
  port: 80
  auth: 
    username: jlr
    password: jlr
  ota: False
  log: False
  version: 2


captive_portal:

# Example configuration entry
sensor:
  - platform: "jsn_sr04t" 
    model: "aj_sr04m"
    name: "Distance"
    update_interval: 1s
    uart_id: mainuart
    unit_of_measurement: m
    
uart:
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO18
  id: mainuart

switch:
  - platform: restart
    name: "Restart Water Tank"